apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  annotations:
    tekton.dev/docker-0: https://index.docker.io/v2/
type: kubernetes.io/dockerconfigjson
stringData:
  .dockerconfigjson: |
    {
      "auths": {
        "https://index.docker.io/v2/": {
          "username": "your-username",               
          "password": "your-personal-access-token"   
        }
      }
    }
# Replace with your access token
 # Replace with your Docker Hub username