apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  # This allows you to add repositories
  repositories: |
    - url: https://github.com/Avy1013/Argo-cd
      username: Avy1013
      password: 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
      type: git






