apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  repositories: |
    - url: https://github.com/Avy1013/Argo-cd
      type: git
      name: my-rails-app
      username: Avy1013
      passwordSecret:
        name: password
        key: "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"
